### ISSUE TITLE
Any difference between Apple Pay completion request and Credit card?

### ISSUE THREAD

**Issue by teo029** [bluesnap/bluesnap-ios#3]
Regarding transaction completion, aren't the requests in both cases (Apple Pay and Credit card) the same?

Do we need to use two different requests?

<img width="946" alt="screen shot 2018-06-06 at 10 57 45 am" src="https://user-images.githubusercontent.com/7328298/41024725-ae1643ae-6978-11e8-96f9-e79ce1e051b0.png">
<img width="970" alt="screen shot 2018-06-06 at 10 57 52 am" src="https://user-images.githubusercontent.com/7328298/41024727-ae4a50c2-6978-11e8-8307-9998f68300f1.png">

**Comment by shevie-bls** [comment]
You are right, the API calls for capture are the same for CC and ApplePay.
They used to be different, but now the calls are the same (since all the details are submitted by the SDK to the BlueSnap server and fetched using the token).
Thank you for pointing it out, we will clear out the duplication in the demo app and the documentation.
